### ISSUE TITLE
Suggestion: Add support for reading MIDI files as MIDIFile classes and editing them

### ISSUE THREAD

**Issue by the-jasoney** [FlipperPA/midi-writer#1]
Adding support for reading MIDI files would create a lot of opportunities, such as writing a tool that can change the mode/scale of the music into a different one or converters that can convert MIDI files into other formats like MusicXML.

**Comment by FlipperPA** [comment]
@the-jasoney There are other tools out there that do a fine job with reading MIDI files; I was trying to keep with the Pythonic package spirit of "doing one thing and one thing well", which is programmatic writing of MIDI files.
