### ISSUE TITLE
Suggestion: use the term 'velocity' instead of 'volume'

### ISSUE THREAD

**Issue by etsuko-fm** [FlipperPA/midi-writer#2]
The MIDI standard refers to note's velocity instead of volume; it'd be good to stick with that convention.
https://en.wikipedia.org/wiki/MIDI#Messages

As you're anyway in the progress of updating this lib, it'd be a nice enhancement. 

For example here:
https://github.com/FlipperPA/midi-writer/blob/main/midi_writer/__init__.py#L118

Happy to submit a PR btw.

**Comment by FlipperPA** [comment]
I'm torn on this. While `velocity` is the term used in the sprawling MIDI spec, `volume` feels more Pythonic to me in that more people will understand what it means and readability counts. Let me think on this.

**Comment by etsuko-fm** [comment]
Thanks for considering. 

Maybe good to realise - also in practice, velocity isn’t volume. It originally refers to with what speed your finger hits a piano/keyboard, which causes different timbres - more overtones from the hammer hitting the strings, a bit more noise, sound ringing on for longer - so not only different volumes. Due to the memory limitations of early MIDI sound libraries, volume changes are what it boiled down to often back in the days - but anno 2022 there’s a lot more sonic detail in any VST/AU instrument library that implements velocity. 

Also in (hardware) synthesizers, velocity is often programmed to change harmonics, timbre as well as volume of a sound. 

Another important detail, there’s MIDI CC 7, which is solely intended to change the volume of a channel. https://anotherproducer.com/online-tools-for-musicians/midi-cc-list/

But above all I’d say velocity is the most pythonic as it most accuratey describes the MIDI spec, which is what this lib intends to implement.

**Comment by FlipperPA** [comment]
@etsuko-io You've convinced me and clearly know this stuff better than me - I just use the package for writing my own tracks and saw it needed some Python love. 💯 

Let's do it. Any interest in being a co-maintainer? I'm a firm believer in having multiple people involved as equals in open source. Better ideas, better quality products, and... frankly... a backup system. 😆

**Comment by etsuko-fm** [comment]
Ha, thanks. That’s what I use this package for too, actually. 

It definitely needed some Python love so cool you picked this up. I’d be interested in being a co-maintainer 🙂

**Comment by FlipperPA** [comment]
@etsuko-io Merged and sent you an invite as collaborator!
